### ISSUE TITLE
pathtracing.inl: wrong shadow rays for delta lights

### ISSUE THREAD

**Issue by jampekka** [szellmann/visionaray#29]
When the lights are sampled in `visionray::pathtracing::kernel`, the shadow is cast with max length of `ld` at: https://github.com/szellmann/visionaray/blob/f557d7d206b0ff3431ba634be9d05619d541ad3f/include/visionaray/detail/pathtracing.inl#L155

However, for delta lights `ld` is always set to one (presumably due to handle the solid angle computations later) at: https://github.com/szellmann/visionaray/blob/f557d7d206b0ff3431ba634be9d05619d541ad3f/include/visionaray/detail/pathtracing.inl#L140

Using the proper length for the shadow ray seems to fix this issue. Eg:
```c++
auto lhr = any_hit(shadow_ray, params.prims.begin, params.prims.end, length(ls.pos - hit_rec.isect_pos) - S(2.0f * params.epsilon), isect);
```

**Comment by szellmann** [comment]
Good catch! With the current code and delta lights, `max_t` for calculating shadow rays is always `1-2*EPSILON`. Just using the shadow ray's length instead of `ld` for `max_t` seems like a proper fix to me, too. Thanks for reporting!
